### ISSUE TITLE
No colors

### ISSUE THREAD

**Issue by kalekume** [zopencommunity/vimport#59]
I don't see colors in vim. I use a xterm-256color terminal.

![image](https://github.com/ZOSOpenTools/vimport/assets/63711967/c5a100ad-9beb-4dcd-9427-a7d432e178a8)

This is my .vimrc file:

![image](https://github.com/ZOSOpenTools/vimport/assets/63711967/871cc922-60df-46d7-8a63-5aee8e27c0ed)

When I edit any file there are no colors:

![image](https://github.com/ZOSOpenTools/vimport/assets/63711967/7db0b94b-833f-45c1-896b-9f7183d26c1a)

**Comment by IgorTodorovskiIBM** [comment]
How did you install vim? Did you use `zopen install vim`? If you manually installed it, you'll also need ncurses in the correct location

**Comment by kalekume** [comment]
You were right, ncurses was installed but not loaded.

Thank you very much for your help.

**Comment by kalekume** [comment]
another topic, is it possible to have the ls command colourised?

**Comment by MikeFultonDev** [comment]
@kalekume I am going to close off this issue - please open up a separate issue for 'ls' - that should go under 'coreutilsport' I believe (@IgorTodorovskiIBM correct me if I'm wrong).
